### ISSUE TITLE
Possible infinite loop in gamelogic when picking team colours

### ISSUE THREAD

**Issue by dddeeefff** [ojbMMXV/minecraft-tower-control#1]
Possible recursion issue nearby the comment

"Run recursively until it does not equal an existing team's color"

https://github.com/ojbMMXV/minecraft-tower-control/blob/master/src/main/java/ojbmmxv/towercontrol/util/GameLogic.java

Could this run forever if all team colours were taken?

**Comment by ojbMMXV** [comment]
Theoretically yes, however it won't happen unless the constant value which declares the max number of teams is modified. 

Will fix
